name: Main Action

on: repository_dispatch
    types: [fire-missile]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Perform action
      run: |
        echo "Missile hits the target."
